project:
  type: website
  preview:
    port: 3000
    browser: false

website:
  title: "GRETL"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - getting_started.qmd
      - text: "Documentation"
        menu: 
          - text: "Reference"
            href: reference.qmd
          - text: "Deployment"
            href: deployment.qmd
          - text: "Development"
            href: development.qmd

      - text: "Help"
        menu:
          - text: "Report an Issue"
            icon: bug
            href: https://github.com/sogis/gretl/issues
          - text: "Discussions"
            icon: chat-right-text
            href: https://github.com/sogis/gretl/discussions/
          # - text: "FAQ"
          #   icon: question-circle
          #   href: getting_started.ipynb#faq
    right:
      - icon: github
        href: https://github.com/sogis/gretl
        aria-label: GitHub
  # sidebar:
  #   style: floating
  #   contents: auto
  page-footer: 
    left: "Copyright 2024, Amt für Geoinformation Kanton Solothurn" 
    right: 
      - icon: github
        href: https://github.com/sogis
      - icon: twitter 
        href: https://twitter.com/_sogis 

format:
  html:
    theme: cosmo
    css: styles.css
    header-includes: |
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet">
    mainfont: Inter
    toc: true
    toc-depth: 3
    grid:
      sidebar-width: 300px
      margin-width: 300px
      body-width: 1200px

