on:
  workflow_dispatch:
    inputs:
      gretlbranch:
        description: 'GRETL Branch'
        required: true
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout GRETL repo 
      - uses: actions/checkout@v4
        with:
          repository: sogis/gretl
          path: gretl
          ref: V3_0_doclet

      - name: Debug 1
        working-directory: gretl
        run: |
          pwd
          ls -la

      - name: Get commit SHA from GRETL repo
        working-directory: gretl
        id: get_commit_sha
        run: echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Display Commit SHA
        run: echo "The current commit SHA is ${{ env.COMMIT_SHA }}"



      # - name: Set up Quarto
      #   uses: quarto-dev/quarto-actions/setup@v2

      # - name: Render and Publish
      #   uses: quarto-dev/quarto-actions/publish@v2
      #   with:
      #     target: gh-pages
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create s3 config and credentials file
        run: |
          mkdir ~/.aws/
          touch ~/.aws/config
          touch ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "endpoint_url = ${{secrets.HETZNER_S3_ENDPOINT_URL}}" >> ~/.aws/config
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{secrets.HETZNER_S3_KEY_ID}}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{secrets.HETZNER_S3_SECRET_ACCESS_KEY}}" >> ~/.aws/credentials

      - name: Debug 1
        run: |
          cat ~/.aws/config
          cat ~/.aws/credentials

      - name: Debug 2
        run: |
          aws s3 ls --region fsn1

      - name: Publish to S3
        run: aws s3 cp _site s3://ch-agi-geodaten-dev/Vx_y_z --recursive --region fsn1

        # with:
        #   aws_key_id: ${{ secrets.HETZNER_S3_KEY_ID }}
        #   aws_secret_access_key: ${{ secrets.HETZNER_S3_SECRET_ACCESS_KEY}}
        #   #aws_bucket: ${{ secrets.AWS_BUCKET }}
        #   aws_bucket: ch-agi-geodaten-dev
        #   source_dir: '_site'
