on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create s3 config and credentials file
        run: |
          mkdir ~/.aws/
          touch ~/.aws/config
          touch ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "endpoint_url = ${{secrets.HETZNER_S3_ENDPOINT_URL}}" >> ~/.aws/config
          echo "[default]\naws_access_key_id = ${{secrets.HETZNER_S3_KEY_ID}}\naws_secret_access_key = ${{secrets.HETZNER_S3_SECRET_ACCESS_KEY}}" > ~/.aws/credentials

      - name: Debug 1
        run: |
          cat ~/.aws/config

        # with:
        #   aws_key_id: ${{ secrets.HETZNER_S3_KEY_ID }}
        #   aws_secret_access_key: ${{ secrets.HETZNER_S3_SECRET_ACCESS_KEY}}
        #   #aws_bucket: ${{ secrets.AWS_BUCKET }}
        #   aws_bucket: ch-agi-geodaten-dev
        #   source_dir: '_site'
